-- This is an empty migration.

INSERT INTO room_type (room_type_name) VALUES ('Labo');
INSERT INTO room_type (room_type_name) VALUES ('Receiving Location');
INSERT INTO room_type (room_type_name) VALUES ('Stockroom');
INSERT INTO room_type (room_type_name) VALUES ('Store Room');

insert into product_type (product_type_name) values ('Bouteille de gaz');
insert into product_type (product_type_name) values ('Produit chimique');
insert into product_type (product_type_name) values ('Autres Articles');

insert into storage_type (storage_type_name) values ('Armoire');
insert into storage_type (storage_type_name) values ('Boite à gants');
insert into storage_type (storage_type_name) values ('Congélateur');
insert into storage_type (storage_type_name) values ('Local extérieur');
insert into storage_type (storage_type_name) values ('Local intérieur');
insert into storage_type (storage_type_name) values ('Rayonnage');
insert into storage_type (storage_type_name) values ('Réfrigérateur');
insert into storage_type (storage_type_name) values ('Autre');

insert into storage_subtype (storage_subtype_name) values ('ATEX');
insert into storage_subtype (storage_subtype_name) values ('Résistant au feu (EI90)');
insert into storage_subtype (storage_subtype_name) values ('Standard');
insert into storage_subtype (storage_subtype_name) values ('Standard (fixée au mur)');
insert into storage_subtype (storage_subtype_name) values ('Standard (fixée sur un support)');
insert into storage_subtype (storage_subtype_name) values ('Standard (ni ventilé, ni résistant au feu)');
insert into storage_subtype (storage_subtype_name) values ('Standard (pas ATEX)');
insert into storage_subtype (storage_subtype_name) values ('Ventilé');
insert into storage_subtype (storage_subtype_name) values ('Ventilé et résistant au feu (EI90)');
insert into storage_subtype (storage_subtype_name) values ('Autre');


insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 2, 1, 6);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 2, 1, 8);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 2, 1, 9);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 2, 7, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 2, 7, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 2, 3, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 2, 3, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 2, 6, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 2, 8, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 2, 8, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 2, 2, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 1, 1, 6);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 1, 1, 2);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 1, 1, 9);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 1, 5, 4);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 1, 4, 5);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 3, 1, 6);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 3, 7, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 3, 7, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 3, 3, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 3, 3, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 3, 6, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (1, 3, 8, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 2, 1, 6);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 2, 1, 8);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 2, 1, 9);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 2, 7, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 2, 7, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 2, 3, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 2, 3, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 2, 6, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 2, 8, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 2, 8, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 1, 1, 6);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 1, 1, 2);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 1, 1, 9);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 1, 5, 4);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 1, 4, 5);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 3, 1, 6);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 3, 7, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 3, 7, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 3, 3, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 3, 3, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 3, 6, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (3, 3, 8, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 2, 1, 6);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 2, 1, 8);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 2, 1, 9);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 2, 7, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 2, 7, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 2, 3, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 2, 3, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 2, 6, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 2, 8, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 2, 8, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 1, 1, 6);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 1, 1, 2);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 1, 1, 9);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 1, 5, 4);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 1, 4, 5);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 3, 1, 6);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 3, 7, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 3, 3, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 3, 6, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (4, 3, 8, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 2, 1, 6);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 2, 1, 8);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 2, 1, 9);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 2, 7, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 2, 7, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 2, 3, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 2, 3, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 2, 6, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 2, 8, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 2, 8, 1);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 1, 1, 6);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 1, 1, 2);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 1, 1, 9);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 1, 5, 4);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 1, 4, 5);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 3, 1, 6);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 3, 7, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 3, 3, 7);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 3, 6, 3);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype) values (2, 3, 8, 3);
