-- This is an empty migration.

INSERT INTO room_type (symbol, short_name) VALUES ('LABO', 'L');
INSERT INTO room_type (symbol, short_name) VALUES ('RCVLC', 'T');
INSERT INTO room_type (symbol, short_name) VALUES ('STKRM', 'S');
INSERT INTO room_type (symbol, short_name) VALUES ('STRRM', 'R');

insert into product_type (symbol, short_name) values ('GASBP', 'G');
insert into product_type (symbol, short_name) values ('CHEMP', 'C');
insert into product_type (symbol, short_name) values ('OTHER', 'A');

insert into storage_type (symbol, short_name) values ('ARMRE', 'A');
insert into storage_type (symbol, short_name) values ('GLVBX', 'B');
insert into storage_type (symbol, short_name) values ('FREEZ', 'C');
insert into storage_type (symbol, short_name) values ('EXLOC', 'E');
insert into storage_type (symbol, short_name) values ('INLOC', 'I');
insert into storage_type (symbol, short_name) values ('SHLVG', 'Y');
insert into storage_type (symbol, short_name) values ('FRDGE', 'R');
insert into storage_type (symbol, short_name) values ('OTHER', 'U');

insert into storage_subtype (symbol, short_name) values ('ATEX', 'A');
insert into storage_subtype (symbol, short_name) values ('FR90', 'R');
insert into storage_subtype (symbol, short_name) values ('STDRD', 'S');
insert into storage_subtype (symbol, short_name) values ('VENTD', 'V');
insert into storage_subtype (symbol, short_name) values ('VFR90', 'F');
insert into storage_subtype (symbol, short_name) values ('OTHER', 'X');

insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 1, 4, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 7, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 3, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 8, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 2, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 1, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 1, 1, 2, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 1, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 1, 5, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 1, 4, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 7, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 3, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 1, 4, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 7, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 3, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 1, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 1, 1, 2, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 1, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 1, 5, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 1, 4, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 7, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 3, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 1, 4, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 7, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 3, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 8, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 1, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 1, 1, 2, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 1, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 1, 5, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 1, 4, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 3, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 3, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 3, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 3, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 3, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 1, 4, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 7, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 3, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 8, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 1, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 1, 1, 2, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 1, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 1, 5, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 1, 4, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 3, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 3, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 3, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 3, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 3, 8, 3, true, true);
