-- This is an empty migration.

INSERT INTO room_type (name, short_name) VALUES ('Labo', 'L');
INSERT INTO room_type (name, short_name) VALUES ('Receiving Location', 'T');
INSERT INTO room_type (name, short_name) VALUES ('Stockroom', 'S');
INSERT INTO room_type (name, short_name) VALUES ('Storeroom', 'R');

insert into product_type (name, short_name) values ('Bouteille de gaz', 'G');
insert into product_type (name, short_name) values ('Produit chimique', 'C');
insert into product_type (name, short_name) values ('Autres Articles', 'A');

insert into storage_type (name, short_name) values ('Armoire', 'A');
insert into storage_type (name, short_name) values ('Boite à gants', 'B');
insert into storage_type (name, short_name) values ('Congélateur', 'C');
insert into storage_type (name, short_name) values ('Local extérieur', 'E');
insert into storage_type (name, short_name) values ('Local intérieur', 'I');
insert into storage_type (name, short_name) values ('Rayonnage', 'Y');
insert into storage_type (name, short_name) values ('Réfrigérateur', 'R');
insert into storage_type (name, short_name) values ('Autre', 'U');

insert into storage_subtype (name, short_name) values ('ATEX', 'A');
insert into storage_subtype (name, short_name) values ('Résistant au feu (EI90)', 'R');
insert into storage_subtype (name, short_name) values ('Standard', 'S');
insert into storage_subtype (name, short_name) values ('Ventilé', 'V');
insert into storage_subtype (name, short_name) values ('Ventilé et résistant au feu (EI90)', 'F');
insert into storage_subtype (name, short_name) values ('Autre', 'X');

insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 1, 4, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 7, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 3, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 8, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 2, 2, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 1, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 1, 1, 2, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 1, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 1, 5, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 1, 4, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 7, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 3, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (1, 3, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 1, 4, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 7, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 3, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 2, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 1, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 1, 1, 2, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 1, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 1, 5, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 1, 4, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 7, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 3, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (3, 3, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 1, 4, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 7, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 3, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 2, 8, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 1, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 1, 1, 2, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 1, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 1, 5, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 1, 4, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 3, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 3, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 3, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 3, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (4, 3, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 1, 4, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 7, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 3, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 8, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 2, 8, 1, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 1, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 1, 1, 2, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 1, 1, 5, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 1, 5, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 1, 4, 3, false, false);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 3, 1, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 3, 7, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 3, 3, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 3, 6, 3, true, true);
insert into allowed_type_values (id_room_type, id_product_type, id_storage_type, id_storage_subtype, allows_shelves, allows_boxes) values (2, 3, 8, 3, true, true);
